package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/go-faster/errors"
)

// pkgVersion is one top-level entry of versions.nix: a pinned version plus,
// per Nix system, whatever fields that package's fetchurl/fetchzip call
// needs (platform/target/arch/url/... - varies per package) including "hash".
type pkgVersion struct {
	Version   string                       `json:"version"`
	Artifacts map[string]map[string]string `json:"artifacts"`
}

type versions map[string]pkgVersion

// readVersions evaluates versions.nix through `nix eval --json` rather than
// parsing Nix syntax in Go - it's the same shape either way, and this can
// never drift from what the flake itself actually sees.
func readVersions(ctx context.Context, path string) (versions, error) {
	out, err := exec.CommandContext(ctx, "nix", "eval", "--json", "--file", path).Output()
	if err != nil {
		return nil, errors.Wrapf(err, "nix eval --json --file %s", path)
	}
	var v versions
	if err := json.Unmarshal(out, &v); err != nil {
		return nil, errors.Wrap(err, "parse nix eval output")
	}
	return v, nil
}

// writeVersions renders v as a fresh versions.nix (not a patch - the whole
// file is regenerated from the in-memory state) and formats it with nixfmt.
func writeVersions(ctx context.Context, path string, v versions) error {
	if err := os.WriteFile(path, []byte(renderVersions(v)), 0o644); err != nil {
		return errors.Wrap(err, "write versions.nix")
	}
	cmd := exec.CommandContext(ctx, "nix", "run", "nixpkgs#nixfmt", "--", path)
	if out, err := cmd.CombinedOutput(); err != nil {
		return errors.Wrapf(err, "nixfmt %s: %s", path, out)
	}
	return nil
}

func renderVersions(v versions) string {
	var b strings.Builder
	b.WriteString("# Generated by tools/bump - do not edit by hand.\n")
	b.WriteString("# Regenerate with: cd tools/bump && go run . -write\n")
	b.WriteString("{\n")
	for i, name := range sortedSystems(v) {
		if i > 0 {
			b.WriteString("\n")
		}
		pkg := v[name]
		fmt.Fprintf(&b, "  %s = {\n", name)
		fmt.Fprintf(&b, "    version = %s;\n", nixString(pkg.Version))
		b.WriteString("    artifacts = {\n")
		for _, system := range sortedSystems(pkg.Artifacts) {
			fields := pkg.Artifacts[system]
			fmt.Fprintf(&b, "      %s = {\n", system)
			for _, field := range sortedSystems(fields) {
				fmt.Fprintf(&b, "        %s = %s;\n", field, nixString(fields[field]))
			}
			b.WriteString("      };\n")
		}
		b.WriteString("    };\n")
		b.WriteString("  };\n")
	}
	b.WriteString("}\n")
	return b.String()
}

// nixString renders a Go string as a double-quoted Nix string literal.
func nixString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"' || c == '\\':
			b.WriteByte('\\')
			b.WriteByte(c)
		case c == '$' && i+1 < len(s) && s[i+1] == '{':
			b.WriteString(`\$`)
		default:
			b.WriteByte(c)
		}
	}
	b.WriteByte('"')
	return b.String()
}
