{
  description = "A minimal flake template that you can adapt to your own project";

  inputs.nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0";

  outputs =
    { self, ... }@inputs:
    let
      inherit (inputs.nixpkgs) lib;

      # Versions/urls/hashes for every packaged tool - regenerated wholesale by
      # tools/bump instead of hand-edited, so it's kept out of the rest of this
      # file's logic (builders, PKGBUILD generation, package wiring).
      versions = import ./versions.nix;

      supportedSystems = [
        "x86_64-linux"
        "aarch64-linux"
        "aarch64-darwin"
      ];

      forEachSupportedSystem =
        f:
        lib.genAttrs supportedSystems (
          system:
          f {
            inherit system;
            pkgs = import inputs.nixpkgs {
              inherit system;
              config.allowUnfree = true;
            };
          }
        );

      packageMeta = {
        license = lib.licenses.unfree;
        sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
      };

      mkBinaryPackage =
        pkgs:
        {
          pname,
          version,
          src,
          executableName ? pname,
          extraExecutables ? [ ],
          postInstall ? "",
          meta ? { },
        }:
        pkgs.stdenvNoCC.mkDerivation {
          inherit
            pname
            version
            src
            postInstall
            ;

          dontUnpack = true;
          dontStrip = true;

          installPhase = ''
            runHook preInstall

            install -Dm755 $src $out/bin/${executableName}
          ''
          + lib.concatMapStringsSep "\n" (name: ''
            ln -s ${executableName} $out/bin/${name}
          '') extraExecutables
          + ''

            runHook postInstall
          '';

          meta = packageMeta // meta;
        };

      mkTarballPackage =
        pkgs:
        {
          pname,
          version,
          src,
          binaryPath,
          executableName ? pname,
          meta ? { },
        }:
        pkgs.stdenvNoCC.mkDerivation {
          inherit pname version src;

          dontStrip = true;
          sourceRoot = ".";

          installPhase = ''
            runHook preInstall

            mkdir -p $out/share/${pname} $out/bin
            cp -R . $out/share/${pname}/
            chmod -R u+w $out/share/${pname}
            chmod 755 $out/share/${pname}/${binaryPath}
            ln -s $out/share/${pname}/${binaryPath} $out/bin/${executableName}

            runHook postInstall
          '';

          meta = packageMeta // meta;
        };

      mkZipPackage =
        pkgs:
        {
          pname,
          version,
          url,
          hash,
          binaryPath ? pname,
          executableName ? pname,
          meta ? { },
        }:
        pkgs.stdenvNoCC.mkDerivation {
          inherit pname version;
          src = pkgs.fetchzip {
            inherit url hash;
            stripRoot = false;
          };

          dontStrip = true;

          installPhase = ''
            runHook preInstall

            mkdir -p $out/share/${pname} $out/bin
            cp -R $src/. $out/share/${pname}/
            chmod -R u+w $out/share/${pname}
            chmod 755 $out/share/${pname}/${binaryPath}
            ln -s $out/share/${pname}/${binaryPath} $out/bin/${executableName}

            runHook postInstall
          '';

          meta = packageMeta // meta;
        };

      grokVersion = versions.grok.version;
      grokArtifacts = versions.grok.artifacts;

      codexVersion = versions.codex.version;
      codexArtifacts = versions.codex.artifacts;

      claudeCodeVersion = versions.claude-code.version;
      claudeCodeArtifacts = versions.claude-code.artifacts;
      claudeCodeUrl =
        platform:
        "https://downloads.claude.ai/claude-code-releases/${claudeCodeVersion}/${platform}/claude";

      # Shared by the Nix package's wrapper and the generated PKGBUILD's package(), so the
      # "disable Claude's own updater/health-check" behavior only needs to be declared once.
      claudeCodeWrapperEnv = {
        DISABLE_UPDATES = "1";
        DISABLE_INSTALLATION_CHECKS = "1";
      };
      claudeCodeWrapperExports = lib.concatStrings (
        lib.mapAttrsToList (name: value: "export ${name}=${value}\n") claudeCodeWrapperEnv
      );

      # Renders a pacman PKGBUILD from the same version/url/hash data used to build the Nix
      # package, via Nix string interpolation, instead of hand-writing (and drifting from) a
      # separate copy. `artifacts` is keyed by pacman arch name (x86_64, aarch64), each an
      # { url, sha256Hex } pair.
      mkPkgbuild =
        {
          pname,
          pkgname ? "${pname}-bin",
          version,
          description,
          homepage,
          license ? "LicenseRef-${pname}",
          artifacts,
          packageBody,
        }:
        ''
          # Generated by flake.nix's mkPkgbuild for the '${pname}' package - do not edit by hand.
          # Regenerate with: nix run .#gen-pkgbuilds
          pkgname=${pkgname}
          pkgver=${version}
          pkgrel=1
          pkgdesc="${description}"
          arch=(${lib.concatMapStringsSep " " (arch: "'${arch}'") (lib.attrNames artifacts)})
          url="${homepage}"
          license=('${license}')
          options=('!strip')
          provides=('${pname}')
          conflicts=('${pname}')
        ''
        + lib.concatStrings (
          lib.mapAttrsToList (
            arch: a: ''source_${arch}=("$pkgname-$pkgver-${arch}::${a.url}")'' + "\n"
          ) artifacts
        )
        + lib.concatStrings (
          lib.mapAttrsToList (arch: a: "sha256sums_${arch}=('${a.sha256Hex}')\n") artifacts
        )
        + ''

          package() {
          ${packageBody}
          }
        '';

      claudeCodePkgbuildArtifacts =
        lib.mapAttrs
          (
            arch: system:
            let
              a = claudeCodeArtifacts.${system};
            in
            {
              url = claudeCodeUrl a.platform;
              sha256Hex = builtins.convertHash {
                hash = a.hash;
                toHashFormat = "base16";
                hashAlgo = "sha256";
              };
            }
          )
          {
            x86_64 = "x86_64-linux";
            aarch64 = "aarch64-linux";
          };

      claudeCodePkgbuild = mkPkgbuild {
        pname = "claude-code";
        version = claudeCodeVersion;
        description = "Claude Code CLI";
        homepage = "https://claude.ai/code";
        artifacts = claudeCodePkgbuildArtifacts;
        packageBody = ''
          install -Dm755 "$srcdir/$pkgname-$pkgver-$CARCH" "$pkgdir/opt/$pkgname/bin/claude"
          install -dm755 "$pkgdir/usr/bin"
          cat > "$pkgdir/usr/bin/claude" << 'INNEREOF'
          #!/bin/sh
        ''
        + claudeCodeWrapperExports
        + ''
          exec /opt/$pkgname/bin/claude "$@"
          INNEREOF
            chmod 755 "$pkgdir/usr/bin/claude"'';
      };

      pkgbuildArchMap = {
        x86_64 = "x86_64-linux";
        aarch64 = "aarch64-linux";
      };

      # For fetchurl-based packages, the pinned hash already *is* the raw file hash
      # pacman's sha256sums needs - just convert it to hex.
      mkRawPkgbuildArtifacts =
        urlFor: artifactsTable:
        lib.mapAttrs (
          arch: system:
          let
            a = artifactsTable.${system};
          in
          {
            url = urlFor a;
            sha256Hex = builtins.convertHash {
              hash = a.hash;
              toHashFormat = "base16";
              hashAlgo = "sha256";
            };
          }
        ) pkgbuildArchMap;

      # For fetchzip-based packages (vibe/vibe-acp), the pinned hash is a NAR hash of
      # the *unpacked* tree (see tools/bump's fetchZip), not the raw archive bytes
      # pacman needs - there's no way to derive that from flake.nix alone. Emit a
      # per-arch placeholder instead; gen-pkgbuilds fetches+hashes the raw file
      # itself and sed-replaces these (see the vibe/vibe-acp branch below).
      mkPendingPkgbuildArtifacts =
        urlFor: artifactsTable:
        lib.mapAttrs (arch: system: {
          url = urlFor artifactsTable.${system};
          sha256Hex = "__HASH_${lib.toUpper arch}__";
        }) pkgbuildArchMap;

      mkBinaryPkgbuildBody =
        {
          binName,
          extraBins ? [ ],
        }:
        ''
          install -Dm755 "$srcdir/$pkgname-$pkgver-$CARCH" "$pkgdir/usr/bin/${binName}"
        ''
        + lib.concatMapStrings (extra: ''
          ln -s ${binName} "$pkgdir/usr/bin/${extra}"
        '') extraBins;

      mkTarballPkgbuildBody =
        { binaryPath, binName }:
        ''
          rm -f "$pkgname-$pkgver-$CARCH"
          install -dm755 "$pkgdir/usr/share/$pkgname"
          cp -r . "$pkgdir/usr/share/$pkgname/"
          chmod -R u+w "$pkgdir/usr/share/$pkgname"
          chmod 755 "$pkgdir/usr/share/$pkgname/${binaryPath}"
          install -dm755 "$pkgdir/usr/bin"
          ln -s "/usr/share/$pkgname/${binaryPath}" "$pkgdir/usr/bin/${binName}"
        '';

      grokUrl = platform: "https://x.ai/cli/grok-${grokVersion}-${platform}";
      grokPkgbuild = mkPkgbuild {
        pname = "grok-cli";
        version = grokVersion;
        description = "Grok CLI";
        homepage = "https://x.ai/cli";
        artifacts = mkRawPkgbuildArtifacts (a: grokUrl a.platform) grokArtifacts;
        packageBody = mkBinaryPkgbuildBody {
          binName = "grok";
          extraBins = [ "agent" ];
        };
      };

      codexUrl =
        target:
        "https://github.com/openai/codex/releases/download/rust-v${codexVersion}/codex-package-${target}.tar.gz";
      codexPkgbuild = mkPkgbuild {
        pname = "codex-cli";
        version = codexVersion;
        description = "OpenAI Codex CLI";
        homepage = "https://github.com/openai/codex";
        artifacts = mkRawPkgbuildArtifacts (a: codexUrl a.target) codexArtifacts;
        packageBody = mkTarballPkgbuildBody {
          binaryPath = "bin/codex";
          binName = "codex";
        };
      };

      copilotUrl =
        platform:
        "https://github.com/github/copilot-cli/releases/download/v${copilotVersion}/copilot-${platform}.tar.gz";
      copilotPkgbuild = mkPkgbuild {
        pname = "copilot-cli";
        version = copilotVersion;
        description = "GitHub Copilot CLI";
        homepage = "https://github.com/github/copilot-cli";
        artifacts = mkRawPkgbuildArtifacts (a: copilotUrl a.platform) copilotArtifacts;
        packageBody = mkTarballPkgbuildBody {
          binaryPath = "copilot";
          binName = "copilot";
        };
      };

      # Linux-only here (PKGBUILDs never target darwin), so this always resolves to
      # opencode's .tar.gz/fetchurl artifacts, never its darwin .zip/fetchzip one -
      # no NAR-hash pending-placeholder dance needed, unlike vibe/vibe-acp.
      opencodeUrl =
        platform:
        "https://github.com/anomalyco/opencode/releases/download/v${opencodeVersion}/opencode-${platform}.tar.gz";
      opencodePkgbuild = mkPkgbuild {
        pname = "opencode";
        version = opencodeVersion;
        description = "opencode CLI";
        homepage = "https://github.com/anomalyco/opencode";
        artifacts = mkRawPkgbuildArtifacts (a: opencodeUrl a.platform) opencodeArtifacts;
        packageBody = mkTarballPkgbuildBody {
          binaryPath = "opencode";
          binName = "opencode";
        };
      };

      kimiUrl =
        platform:
        "https://github.com/MoonshotAI/kimi-cli/releases/download/${kimiVersion}/kimi-${kimiVersion}-${platform}.tar.gz";
      kimiPkgbuild = mkPkgbuild {
        pname = "kimi-cli";
        version = kimiVersion;
        description = "Kimi (Moonshot AI) CLI";
        homepage = "https://github.com/MoonshotAI/kimi-cli";
        artifacts = mkRawPkgbuildArtifacts (a: kimiUrl a.platform) kimiArtifacts;
        packageBody = mkTarballPkgbuildBody {
          binaryPath = "kimi";
          binName = "kimi";
        };
      };

      vibeUrl =
        arch:
        "https://github.com/mistralai/mistral-vibe/releases/download/v${vibeVersion}/vibe-${arch}-${vibeVersion}.zip";
      vibePkgbuildArtifacts = mkPendingPkgbuildArtifacts (a: vibeUrl a.arch) vibeArtifacts;
      vibePkgbuild = mkPkgbuild {
        pname = "mistral-vibe";
        version = vibeVersion;
        description = "Mistral Vibe CLI";
        homepage = "https://github.com/mistralai/mistral-vibe";
        artifacts = vibePkgbuildArtifacts;
        packageBody = mkTarballPkgbuildBody {
          binaryPath = "vibe";
          binName = "vibe";
        };
      };

      vibeAcpUrl =
        arch:
        "https://github.com/mistralai/mistral-vibe/releases/download/v${vibeVersion}/vibe-acp-${arch}-${vibeVersion}.zip";
      vibeAcpPkgbuildArtifacts = mkPendingPkgbuildArtifacts (a: vibeAcpUrl a.arch) vibeAcpArtifacts;
      vibeAcpPkgbuild = mkPkgbuild {
        pname = "mistral-vibe-acp";
        version = vibeVersion;
        description = "Mistral Vibe ACP";
        homepage = "https://github.com/mistralai/mistral-vibe";
        artifacts = vibeAcpPkgbuildArtifacts;
        packageBody = mkTarballPkgbuildBody {
          binaryPath = "vibe-acp";
          binName = "vibe-acp";
        };
      };

      vibeVersion = versions.vibe.version;
      vibeArtifacts = versions.vibe.artifacts;

      vibeAcpArtifacts = versions.vibe-acp.artifacts;

      copilotVersion = versions.copilot.version;
      copilotArtifacts = versions.copilot.artifacts;

      opencodeVersion = versions.opencode.version;
      opencodeArtifacts = versions.opencode.artifacts;

      protonPassVersion = versions.proton-pass.version;
      protonPassArtifacts = versions.proton-pass.artifacts;

      # Built straight from Proton's own release feed instead of nixpkgs' pkgs.proton-pass,
      # which tracks releases slower than upstream. Mirrors nixpkgs' own proton-pass recipe
      # (pkgs/by-name/pr/proton-pass): unpack the vendor .deb/.dmg and repoint app.asar's
      # process.resourcesPath at the store path since the app is launched via system electron.
      mkProtonPassPackage =
        pkgs: system:
        let
          artifact = protonPassArtifacts.${system};
          src = pkgs.fetchurl { inherit (artifact) url hash; };
          meta = packageMeta // {
            description = "Desktop application for Proton Pass";
            homepage = "https://proton.me/pass";
            mainProgram = "proton-pass";
          };
        in
        if pkgs.stdenv.isDarwin then
          pkgs.stdenv.mkDerivation {
            pname = "proton-pass";
            version = protonPassVersion;
            inherit src meta;

            nativeBuildInputs = [ pkgs.undmg ];
            sourceRoot = ".";

            installPhase = ''
              runHook preInstall
              mkdir -p $out/Applications
              cp -r *.app $out/Applications
              runHook postInstall
            '';
          }
        else
          pkgs.stdenvNoCC.mkDerivation {
            pname = "proton-pass";
            version = protonPassVersion;
            inherit src meta;

            nativeBuildInputs = with pkgs; [
              dpkg
              makeWrapper
              asar
            ];

            dontConfigure = true;
            dontBuild = true;

            # dpkg-deb -x fails on chrome-sandbox's SUID bit inside the build sandbox;
            # tar --no-same-permissions applies the umask instead, dropping it (unused here
            # anyway, since the app runs under the system electron, not the bundled one).
            unpackPhase = ''
              runHook preUnpack
              dpkg-deb --fsys-tarfile "$src" | tar -x --no-same-owner --no-same-permissions
              runHook postUnpack
            '';

            preInstall = ''
              asar extract usr/lib/proton-pass/resources/app.asar tmp
              rm usr/lib/proton-pass/resources/app.asar
              substituteInPlace tmp/.webpack/main/index.js \
                --replace-fail "process.resourcesPath" "'$out/share/proton-pass'"
              asar pack tmp/ usr/lib/proton-pass/resources/app.asar
              rm -fr tmp
            '';

            installPhase = ''
              runHook preInstall
              mkdir -p $out/share/proton-pass
              cp -r usr/share/ $out/
              cp -r usr/lib/proton-pass/resources/{app.asar,assets} $out/share/proton-pass/
              runHook postInstall
            '';

            preFixup = ''
              makeWrapper ${lib.getExe pkgs.electron} $out/bin/proton-pass \
                --add-flags $out/share/proton-pass/app.asar \
                --set-default ELECTRON_FORCE_IS_PACKAGED 1 \
                --set-default ELECTRON_IS_DEV 0 \
                --inherit-argv0
            '';
          };

      claudeDesktopVersion = versions.claude-desktop.version;
      claudeDesktopArtifacts = versions.claude-desktop.artifacts;

      # Repackages Anthropic's official .deb (Linux-only beta, no upstream nixpkgs package yet).
      # Keeps the official co-located app tree intact (usr/lib/claude-desktop/{claude-desktop,resources/})
      # so /proc/self/exe and process.resourcesPath resolve correctly inside the store path,
      # instead of running the app under nixpkgs' electron.
      mkClaudeDesktopPackage =
        pkgs: system:
        let
          artifact = claudeDesktopArtifacts.${system};
        in
        pkgs.stdenv.mkDerivation {
          pname = "claude-desktop";
          version = claudeDesktopVersion;

          src = pkgs.fetchurl {
            url = "https://downloads.claude.ai/claude-desktop/apt/stable/pool/main/c/claude-desktop/claude-desktop_${claudeDesktopVersion}_${artifact.arch}.deb";
            inherit (artifact) hash;
          };

          nativeBuildInputs = with pkgs; [
            dpkg
            autoPatchelfHook
            makeWrapper
          ];

          buildInputs = with pkgs; [
            alsa-lib
            at-spi2-atk
            at-spi2-core
            atk
            cairo
            cups
            dbus
            expat
            glib
            gtk3
            libcap_ng
            libgbm
            libseccomp
            libxkbcommon
            nspr
            nss
            pango
            stdenv.cc.cc.lib
            systemd
            libx11
            libxcomposite
            libxdamage
            libxext
            libxfixes
            libxrandr
            libxcb
          ];

          # dlopen'd at runtime rather than DT_NEEDED, so autoPatchelf won't find them on its own.
          runtimeDependencies = map lib.getLib (
            with pkgs;
            [
              libGL
              libayatana-appindicator
              libnotify
              libpulseaudio
              libsecret
              libuuid
              pciutils
              pipewire
              systemd
              wayland
              libxtst
            ]
          );

          # dpkg-deb -x fails on chrome-sandbox's SUID bit inside the build sandbox;
          # tar --no-same-permissions applies the umask instead, dropping it (the store
          # couldn't represent it anyway - relies on unprivileged userns, same as nixpkgs' slack/signal-desktop).
          unpackPhase = ''
            runHook preUnpack
            dpkg-deb --fsys-tarfile "$src" | tar -x --no-same-owner --no-same-permissions
            runHook postUnpack
          '';

          dontConfigure = true;
          dontBuild = true;
          dontStrip = true;

          installPhase = ''
            runHook preInstall

            mkdir -p $out
            cp -a usr/lib usr/share $out/
            makeWrapper $out/lib/claude-desktop/claude-desktop \
              $out/bin/claude-desktop \
              --prefix VK_ADD_DRIVER_FILES : \
                "${pkgs.addDriverRunpath.driverLink}/share/vulkan/icd.d"

            runHook postInstall
          '';

          preFixup = ''
            addAutoPatchelfSearchPath "$out/lib/claude-desktop"
          '';

          # The bundled ANGLE libs dlopen the glvnd EGL dispatcher by soname and only
          # carry their own DT_NEEDED on their runpath, so libGL must be added explicitly.
          appendRunpaths = [
            "${lib.getLib pkgs.libGL}/lib"
            "${pkgs.addDriverRunpath.driverLink}/lib"
          ];

          meta = packageMeta // {
            description = "Claude Desktop for Linux (repackaged official .deb)";
            homepage = "https://claude.ai";
            mainProgram = "claude-desktop";
          };
        };

      kimiVersion = versions.kimi.version;
      kimiArtifacts = versions.kimi.artifacts;
    in
    {
      packages = forEachSupportedSystem (
        { pkgs, system }:
        let
          grokArtifact = grokArtifacts.${system};
          codexArtifact = codexArtifacts.${system};
          claudeCodeArtifact = claudeCodeArtifacts.${system};
          copilotArtifact = copilotArtifacts.${system};
          opencodeArtifact = opencodeArtifacts.${system};
          kimiArtifact = kimiArtifacts.${system};

          grok = mkBinaryPackage pkgs {
            pname = "grok-cli";
            version = grokVersion;
            src = pkgs.fetchurl {
              url = "https://x.ai/cli/grok-${grokVersion}-${grokArtifact.platform}";
              inherit (grokArtifact) hash;
            };
            executableName = "grok";
            extraExecutables = [ "agent" ];
            meta = {
              description = "Grok CLI";
              homepage = "https://x.ai/cli";
              mainProgram = "grok";
            };
          };

          codex = mkTarballPackage pkgs {
            pname = "codex-cli";
            version = codexVersion;
            src = pkgs.fetchurl {
              url = "https://github.com/openai/codex/releases/download/rust-v${codexVersion}/codex-package-${codexArtifact.target}.tar.gz";
              inherit (codexArtifact) hash;
            };
            binaryPath = "bin/codex";
            executableName = "codex";
            meta = {
              description = "OpenAI Codex CLI";
              homepage = "https://github.com/openai/codex";
              mainProgram = "codex";
            };
          };

          claude-code = mkBinaryPackage pkgs {
            pname = "claude-code";
            version = claudeCodeVersion;
            src = pkgs.fetchurl {
              url = "https://downloads.claude.ai/claude-code-releases/${claudeCodeVersion}/${claudeCodeArtifact.platform}/claude";
              inherit (claudeCodeArtifact) hash;
            };
            executableName = "claude";
            postInstall = ''
              mv $out/bin/claude $out/bin/.claude-unwrapped
              cat > $out/bin/claude <<'EOF'
              #!${pkgs.runtimeShell}
            ''
            + claudeCodeWrapperExports
            + ''
              exec "$(dirname "$0")/.claude-unwrapped" "$@"
              EOF
              chmod 755 $out/bin/claude
            '';
            meta = {
              description = "Claude Code CLI";
              homepage = "https://claude.ai/code";
              mainProgram = "claude";
            };
          };

          vibeArtifact = vibeArtifacts.${system};
          vibeAcpArtifact = vibeAcpArtifacts.${system};

          vibe = mkZipPackage pkgs {
            pname = "mistral-vibe";
            version = vibeVersion;
            url = "https://github.com/mistralai/mistral-vibe/releases/download/v${vibeVersion}/vibe-${vibeArtifact.arch}-${vibeVersion}.zip";
            inherit (vibeArtifact) hash;
            binaryPath = "vibe";
            executableName = "vibe";
            meta = {
              description = "Mistral Vibe CLI";
              homepage = "https://github.com/mistralai/mistral-vibe";
              mainProgram = "vibe";
            };
          };

          vibe-acp = mkZipPackage pkgs {
            pname = "mistral-vibe-acp";
            version = vibeVersion;
            url = "https://github.com/mistralai/mistral-vibe/releases/download/v${vibeVersion}/vibe-acp-${vibeAcpArtifact.arch}-${vibeVersion}.zip";
            inherit (vibeAcpArtifact) hash;
            binaryPath = "vibe-acp";
            executableName = "vibe-acp";
            meta = {
              description = "Mistral Vibe ACP";
              homepage = "https://github.com/mistralai/mistral-vibe";
              mainProgram = "vibe-acp";
            };
          };

          copilot = mkTarballPackage pkgs {
            pname = "copilot-cli";
            version = copilotVersion;
            src = pkgs.fetchurl {
              url = "https://github.com/github/copilot-cli/releases/download/v${copilotVersion}/copilot-${copilotArtifact.platform}.tar.gz";
              inherit (copilotArtifact) hash;
            };
            binaryPath = "copilot";
            executableName = "copilot";
            meta = {
              description = "GitHub Copilot CLI";
              homepage = "https://github.com/github/copilot-cli";
              mainProgram = "copilot";
            };
          };

          opencode =
            let
              ext = if lib.strings.hasSuffix "darwin" system then "zip" else "tar.gz";
              opencodeUrl = "https://github.com/anomalyco/opencode/releases/download/v${opencodeVersion}/opencode-${opencodeArtifact.platform}.${ext}";
            in
            if ext == "zip" then
              mkZipPackage pkgs {
                pname = "opencode";
                version = opencodeVersion;
                url = opencodeUrl;
                inherit (opencodeArtifact) hash;
                binaryPath = "opencode";
                meta = {
                  description = "opencode CLI";
                  homepage = "https://github.com/anomalyco/opencode";
                  mainProgram = "opencode";
                };
              }
            else
              mkTarballPackage pkgs {
                pname = "opencode";
                version = opencodeVersion;
                src = pkgs.fetchurl {
                  url = opencodeUrl;
                  inherit (opencodeArtifact) hash;
                };
                binaryPath = "opencode";
                meta = {
                  description = "opencode CLI";
                  homepage = "https://github.com/anomalyco/opencode";
                  mainProgram = "opencode";
                };
              };

          kimi = mkTarballPackage pkgs {
            pname = "kimi-cli";
            version = kimiVersion;
            src = pkgs.fetchurl {
              url = "https://github.com/MoonshotAI/kimi-cli/releases/download/${kimiVersion}/kimi-${kimiVersion}-${kimiArtifact.platform}.tar.gz";
              inherit (kimiArtifact) hash;
            };
            binaryPath = "kimi";
            executableName = "kimi";
            meta = {
              description = "Kimi (Moonshot AI) CLI";
              homepage = "https://github.com/MoonshotAI/kimi-cli";
              mainProgram = "kimi";
            };
          };
        in
        {
          inherit
            codex
            copilot
            grok
            kimi
            opencode
            vibe
            vibe-acp
            ;
          inherit claude-code;

          claude = claude-code;
          default = codex;
        }
        // lib.optionalAttrs (claudeDesktopArtifacts ? ${system}) {
          claude-desktop = mkClaudeDesktopPackage pkgs system;
        }
        // lib.optionalAttrs (protonPassArtifacts ? ${system}) {
          proton-pass = mkProtonPassPackage pkgs system;
        }
        // lib.optionalAttrs (lib.strings.hasSuffix "linux" system) {
          grok-pkgbuild = pkgs.writeText "PKGBUILD" grokPkgbuild;
          codex-pkgbuild = pkgs.writeText "PKGBUILD" codexPkgbuild;
          claude-code-pkgbuild = pkgs.writeText "PKGBUILD" claudeCodePkgbuild;
          copilot-pkgbuild = pkgs.writeText "PKGBUILD" copilotPkgbuild;
          opencode-pkgbuild = pkgs.writeText "PKGBUILD" opencodePkgbuild;
          kimi-pkgbuild = pkgs.writeText "PKGBUILD" kimiPkgbuild;
          vibe-pkgbuild = pkgs.writeText "PKGBUILD" vibePkgbuild;
          vibe-acp-pkgbuild = pkgs.writeText "PKGBUILD" vibeAcpPkgbuild;
        }
      );

      devShells = forEachSupportedSystem (
        { pkgs, system }:
        {
          default = pkgs.mkShellNoCC {
            packages = with pkgs; [
              self.formatter.${system}
            ];
          };
        }
      );

      # Copies the generated PKGBUILD(s) from the Nix store into ./pkgbuilds/<name>/PKGBUILD
      # in the working tree, so they can be reviewed and committed. Run with `nix run .#gen-pkgbuilds`.
      apps = forEachSupportedSystem (
        { pkgs, system }:
        lib.optionalAttrs (lib.strings.hasSuffix "linux" system) {
          gen-pkgbuilds = {
            type = "app";
            meta.description = "Write generated PKGBUILDs into ./pkgbuilds/";
            program = toString (
              pkgs.writeShellScript "gen-pkgbuilds" ''
                set -euo pipefail
                export PATH="${
                  lib.makeBinPath [
                    pkgs.curl
                    pkgs.jq
                  ]
                }:$PATH"

                write() {
                  local pkgname="$1" drv="$2"
                  local out="$PWD/pkgbuilds/$pkgname"
                  mkdir -p "$out"
                  install -m644 "$drv" "$out/PKGBUILD"
                  echo "wrote $out/PKGBUILD"
                }

                # For vibe/vibe-acp: fetch+hash the raw zip ourselves (see
                # mkPendingPkgbuildArtifacts) and fill in the placeholders write()
                # left behind.
                resolve_pending() {
                  local pkgname="$1" pending="$2"
                  local out="$PWD/pkgbuilds/$pkgname/PKGBUILD"
                  local arch url hash
                  for arch in x86_64 aarch64; do
                    url=$(jq -r ".$arch" "$pending")
                    echo "  hashing $pkgname/$arch..."
                    hash=$(curl -fsSL "$url" | sha256sum | cut -d' ' -f1)
                    sed -i "s/__HASH_$(echo "$arch" | tr a-z A-Z)__/$hash/" "$out"
                  done
                }

                write grok-cli-bin ${pkgs.writeText "PKGBUILD" grokPkgbuild}
                write codex-cli-bin ${pkgs.writeText "PKGBUILD" codexPkgbuild}
                write claude-code-bin ${pkgs.writeText "PKGBUILD" claudeCodePkgbuild}
                write copilot-cli-bin ${pkgs.writeText "PKGBUILD" copilotPkgbuild}
                write opencode-bin ${pkgs.writeText "PKGBUILD" opencodePkgbuild}
                write kimi-cli-bin ${pkgs.writeText "PKGBUILD" kimiPkgbuild}

                write mistral-vibe-bin ${pkgs.writeText "PKGBUILD" vibePkgbuild}
                resolve_pending mistral-vibe-bin ${
                  pkgs.writeText "vibe-pending.json" (
                    builtins.toJSON (lib.mapAttrs (_: a: a.url) vibePkgbuildArtifacts)
                  )
                }

                write mistral-vibe-acp-bin ${pkgs.writeText "PKGBUILD" vibeAcpPkgbuild}
                resolve_pending mistral-vibe-acp-bin ${
                  pkgs.writeText "vibe-acp-pending.json" (
                    builtins.toJSON (lib.mapAttrs (_: a: a.url) vibeAcpPkgbuildArtifacts)
                  )
                }
              ''
            );
          };
        }
      );

      formatter = forEachSupportedSystem ({ pkgs, ... }: pkgs.nixfmt);
    };
}
