# Generated by tools/bump - do not edit by hand.
# Regenerate with: cd tools/bump && go run . -write
{
  claude-code = {
    version = "2.1.218";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-cauv9ZMSyam2odgYNlBItC5OlcxSGoI2YO3tPgiA2bc=";
        platform = "darwin-arm64";
      };
      aarch64-linux = {
        hash = "sha256-KV/TBIG9A7OEUP3sKm4lu2RywgdPBLDEpWbNWYjyML8=";
        platform = "linux-arm64";
      };
      x86_64-linux = {
        hash = "sha256-4SBxdRqTNrivEBLBAzWP8ErBj5qv9Kc4z/e6XN+vY/I=";
        platform = "linux-x64";
      };
    };
  };

  claude-desktop = {
    version = "1.24012.0";
    artifacts = {
      aarch64-linux = {
        arch = "arm64";
        hash = "sha256-N91dwbC/yzGSVhrL0zy1kDeAb+m5UiGj3fOCRCAxlvE=";
      };
      x86_64-linux = {
        arch = "amd64";
        hash = "sha256-EJaoBjlW+EMP2+UEuxxeAphfMdD0XQguSWbl0w6n46w=";
      };
    };
  };

  codex = {
    version = "0.145.0";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-7Ok3Fp1MnpENYIJqbqSueEihbAiUA9Ei5w59pKxBujQ=";
        target = "aarch64-apple-darwin";
      };
      aarch64-linux = {
        hash = "sha256-VPeaBaum+av475iKvK6L8vzvuiC+tUm0/ys6zbLLb1Q=";
        target = "aarch64-unknown-linux-musl";
      };
      x86_64-linux = {
        hash = "sha256-caKNNiyWrJgpv4IDoscb5FGutyatuEMWf9rw6uj+fdk=";
        target = "x86_64-unknown-linux-musl";
      };
    };
  };

  copilot = {
    version = "1.0.74";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-31iQItVSRCamXSfUX91EVif1qK4el6jhWPotlahMtVQ=";
        platform = "darwin-arm64";
      };
      aarch64-linux = {
        hash = "sha256-miHonctE9dKV8ay22CH/yVyIpC76fy3T/9Bgvm6KZ5c=";
        platform = "linux-arm64";
      };
      x86_64-linux = {
        hash = "sha256-SnCLChy670wspcVGpiL4h6O3DooEMrw87g04ZwSBZlA=";
        platform = "linux-x64";
      };
    };
  };

  grok = {
    version = "0.2.111";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-4fr9//4U8zlGC++vGUNg6PkL/QLv6KTyTPoceuplf/4=";
        platform = "macos-aarch64";
      };
      aarch64-linux = {
        hash = "sha256-0tqtErRIqWyrRhuBlbO1m2PJ+YHpigdBTxLbT8wnjxA=";
        platform = "linux-aarch64";
      };
      x86_64-linux = {
        hash = "sha256-8VjQ1DNnw5WcWtITMnJVrFmRoOxMZ7tHXgnMjNukp7M=";
        platform = "linux-x86_64";
      };
    };
  };

  kimi = {
    version = "1.49.0";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-FQGLILIDruCWWP3GSEDEhG/BfBCNjboaGalVgdPOKSE=";
        platform = "aarch64-apple-darwin";
      };
      aarch64-linux = {
        hash = "sha256-WsVMq84W7eJ7nSBpubiO3uJVKGRue7W++pmAocpx/rs=";
        platform = "aarch64-unknown-linux-gnu";
      };
      x86_64-linux = {
        hash = "sha256-bOC4P1g8RaZMyfUf/n4ajgPueazaaZRfz4wjNBudiS8=";
        platform = "x86_64-unknown-linux-gnu";
      };
    };
  };

  opencode = {
    version = "1.18.4";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-3kJCtcqLxKHFgZSP4v2NXkTQEVz/M9XP409203LGPw0=";
        platform = "darwin-arm64";
      };
      aarch64-linux = {
        hash = "sha256-66h++6OXbVM6JMygMW+O83W1+OeXwKlcJe6RlwC3ujU=";
        platform = "linux-arm64";
      };
      x86_64-linux = {
        hash = "sha256-urRjw/syJNOIu3z61j84cD35zwviz9LOjLSdiGtToXQ=";
        platform = "linux-x64";
      };
    };
  };

  proton-pass = {
    version = "1.38.1";
    artifacts = {
      aarch64-darwin = {
        hash = "sha512-6TtYT8QtlUTD/FkqT0emQKo4mq/2BR6G8MY+F/Z+Urd8cAX9SGDSrrG/NDgZQtVELCOdQSeZZ4DgFNbM/m6CAw==";
        url = "https://proton.me/download/pass/macos/ProtonPass_1.38.1.dmg";
      };
      x86_64-linux = {
        hash = "sha512-4jtjW0CVpZNOH4S1NG+gewXDEkjISzHneTdcPOSIeHOQTHbjtMUriCTZpsG1fBlRftiJeHsvF1aMO38VACFsYg==";
        url = "https://proton.me/download/pass/linux/proton-pass_1.38.1_amd64.deb";
      };
    };
  };

  vibe = {
    version = "2.22.0";
    artifacts = {
      aarch64-darwin = {
        arch = "darwin-aarch64";
        hash = "sha256-PZGHjq8IcGXtqNtJ64UcDsyRM74iU9VszbsFzz+Bhbc=";
      };
      aarch64-linux = {
        arch = "linux-aarch64";
        hash = "sha256-3f+FPHWjvqremPvbAPRtYBgNhIhfXMFZqirxMoIA0ok=";
      };
      x86_64-linux = {
        arch = "linux-x86_64";
        hash = "sha256-WCdBD+d1ij38OGedTTUH915KvqN5cTXFppXy3k1rDCc=";
      };
    };
  };

  vibe-acp = {
    version = "2.22.0";
    artifacts = {
      aarch64-darwin = {
        arch = "darwin-aarch64";
        hash = "sha256-NLr3Zc502ZM+TwpAp4R6fD0DbBW/DIJmmtvUXVd8CY0=";
      };
      aarch64-linux = {
        arch = "linux-aarch64";
        hash = "sha256-Zfj9Tuc2VpPJqvPIkTPOkLdDZ5GYSiDRs+RW31dD96U=";
      };
      x86_64-linux = {
        arch = "linux-x86_64";
        hash = "sha256-LvDS2RyqsVfmdCqCiY4I8LK+ZIneKCavwlzZCNuFjls=";
      };
    };
  };
}
