# Generated by tools/bump - do not edit by hand.
# Regenerate with: cd tools/bump && go run . -write
{
  claude-code = {
    version = "2.1.288";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-u+kwY/egh5oQIbKJHlyTVOWzuYQz4y7+Z1D3cQr+11A=";
        platform = "darwin-arm64";
      };
      aarch64-linux = {
        hash = "sha256-NZq2oFj83pdB3/VJeaIS/RNM346M/C+N4CvDULniudU=";
        platform = "linux-arm64";
      };
      x86_64-linux = {
        hash = "sha256-ApgGi2huf9uvlAKnpYe7f0nAsOCE3gn2kUWgcZIHZAw=";
        platform = "linux-x64";
      };
    };
  };

  claude-desktop = {
    version = "2.9939.4";
    artifacts = {
      aarch64-linux = {
        arch = "arm64";
        hash = "sha256-EI7XnqFksIxPoLtDh97vR3mVez8Pmy2YmONZ82Pr8bw=";
      };
      x86_64-linux = {
        arch = "amd64";
        hash = "sha256-PP3bI78pEeBeJ7TtOFa455XflGQ7LDW1nesxfPmVvKA=";
      };
    };
  };

  codex = {
    version = "0.160.0";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-AH30G2B9u8jSBLl0bOf+0tTObIE/RMMs7uVBdcp5ZSU=";
        target = "aarch64-apple-darwin";
      };
      aarch64-linux = {
        hash = "sha256-fw/kL/Iuz6Oke8SjT1sixCGLQxpOwKulHH2YKZ8HkAw=";
        target = "aarch64-unknown-linux-musl";
      };
      x86_64-linux = {
        hash = "sha256-T8xHq1f1L/dTY5Uah2EUbNEMgoi9hv7UVIfbsgSha3E=";
        target = "x86_64-unknown-linux-musl";
      };
    };
  };

  copilot = {
    version = "1.0.91";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-sp46nkF28uZBdQSRZxQyjQMPBKyTT/Gipt3K2SNchHs=";
        platform = "darwin-arm64";
      };
      aarch64-linux = {
        hash = "sha256-JqQkkb7El6kh8ZjVUKYU4KiYnxwkGPW7HdIVDwnm6sA=";
        platform = "linux-arm64";
      };
      x86_64-linux = {
        hash = "sha256-DnoOhSkCKK/szk1O7UL9qAwPW5yG9DPeskbN4dXuyOU=";
        platform = "linux-x64";
      };
    };
  };

  grok = {
    version = "1.0.46";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-6NqjAjZMnDtqVUbVEc+9GrXl1AepsEKC9mBmXqQF+fM=";
        platform = "macos-aarch64";
      };
      aarch64-linux = {
        hash = "sha256-RbCUPnNvAKJJuc8Cryvp4HSdl8Cab1XPzzApoag28j4=";
        platform = "linux-aarch64";
      };
      x86_64-linux = {
        hash = "sha256-QWJqUykjJBQLklVrnUL/VULj3NBK/4Xq+4aJ3UrbRPw=";
        platform = "linux-x86_64";
      };
    };
  };

  kimi = {
    version = "1.52.0";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-Q/4JH3C7+IYJdCAPkCGgVomgIIV8yZJtVvFQXw0NXLg=";
        platform = "aarch64-apple-darwin";
      };
      aarch64-linux = {
        hash = "sha256-ngbuqWJzYArtSFsfC+3albcITbTyLPKGFP4gE4kzUHo=";
        platform = "aarch64-unknown-linux-gnu";
      };
      x86_64-linux = {
        hash = "sha256-pnYgT3gE7V2uh2UqnWb1eOBxjVAmycsb+jK5perOQgg=";
        platform = "x86_64-unknown-linux-gnu";
      };
    };
  };

  opencode = {
    version = "1.18.34";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-s6SUKb4GH4sD8aGsCig5Krad6TIcUP9hwXjOGrofr6E=";
        platform = "darwin-arm64";
      };
      aarch64-linux = {
        hash = "sha256-u9s/AMLFHkLjFVJSMxUTCXJCJqh3bajpFF47D6PVMQ8=";
        platform = "linux-arm64";
      };
      x86_64-linux = {
        hash = "sha256-DyJHlkcibR0t2ZWV0gCC7nvaOHC2LcapC0Hvwacdfpo=";
        platform = "linux-x64";
      };
    };
  };

  proton-pass = {
    version = "1.41.1";
    artifacts = {
      aarch64-darwin = {
        hash = "sha512-8Mw53nt+SFWlF+TV5+kas4etvniKksm30gp4WHcGM0sTyvHlZTEYwB9j3Iix9mhfN99kCoE0E0Ndo1OtOWa2QQ==";
        url = "https://proton.me/download/pass/macos/ProtonPass_1.38.1.dmg";
      };
      x86_64-linux = {
        hash = "sha512-pLsOkCcND9576yqnqZoVlfw7w/vhrgBi6ELTh83UahfCTFs23TWj+je9a4eduhI7Xn1Kejz2eSNuG4teQWs0wg==";
        url = "https://proton.me/download/pass/linux/proton-pass_1.38.1_amd64.deb";
      };
    };
  };

  vibe = {
    version = "2.25.8";
    artifacts = {
      aarch64-darwin = {
        arch = "darwin-aarch64";
        hash = "sha256-AunLcMANE4vSKbHsq2ck9TFNnBsQdVTK/lBowCjFtTE=";
      };
      aarch64-linux = {
        arch = "linux-aarch64";
        hash = "sha256-kO2ZrfMMEI5Z4wZ/wcjCC1HCjngQTDZ1S6VG7M/gnPk=";
      };
      x86_64-linux = {
        arch = "linux-x86_64";
        hash = "sha256-c3HNU0l+pAESfJE20Tm73ziUC6sjNu0GiwENu+4rUKI=";
      };
    };
  };

  vibe-acp = {
    version = "2.25.8";
    artifacts = {
      aarch64-darwin = {
        arch = "darwin-aarch64";
        hash = "sha256-cSodREshQptS6Kci+4qUsT4stxpesykLrYoN2nCAsno=";
      };
      aarch64-linux = {
        arch = "linux-aarch64";
        hash = "sha256-+vRebHio28ftmyj+HwPC56VZ6xSRJn9DPnWLQcn6/To=";
      };
      x86_64-linux = {
        arch = "linux-x86_64";
        hash = "sha256-pW0fDUkeQvDI8/JaNSDEtCjsFEUX81iXErW/OLcOHbw=";
      };
    };
  };
}
