# Generated by tools/bump - do not edit by hand.
# Regenerate with: cd tools/bump && go run . -write
{
  claude-code = {
    version = "2.1.296";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-ybU0Fje+y9Qj3f/FslSvtkVoKjhoy3CLvGzA57tBmTc=";
        platform = "darwin-arm64";
      };
      aarch64-linux = {
        hash = "sha256-8fbpbg2DQrnb9B1+iCVTl6alLOPYc2rWpMa1nJti/vo=";
        platform = "linux-arm64";
      };
      x86_64-linux = {
        hash = "sha256-JJcuO8hZ+rK0btTB5R99YTDwbTvVUIEaEUZA3jNw0N4=";
        platform = "linux-x64";
      };
    };
  };

  claude-desktop = {
    version = "2.31226.1";
    artifacts = {
      aarch64-linux = {
        arch = "arm64";
        hash = "sha256-0vV6OP/HPP2mYPh3Kl+LraBebXQ5mUiiaMb11TWT7o8=";
      };
      x86_64-linux = {
        arch = "amd64";
        hash = "sha256-Wpvr38sd9s44dns3Pzp/q/dxVqLd2KP10Elh2lveMF4=";
      };
    };
  };

  codex = {
    version = "0.162.1";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-iON8zd9aD06p3BvhPGaiqU+cLRoE86zpBT1xs5OeiF0=";
        target = "aarch64-apple-darwin";
      };
      aarch64-linux = {
        hash = "sha256-U6nOC5S+snpj/esvdwTZUZnheziYqjO2BGGhqTrA2Is=";
        target = "aarch64-unknown-linux-musl";
      };
      x86_64-linux = {
        hash = "sha256-pnb1ciquDYbL43ZDMvCOqx/didwKMAs61P+/SGEfo+M=";
        target = "x86_64-unknown-linux-musl";
      };
    };
  };

  copilot = {
    version = "1.0.95";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-3o/o+EUSR/A+DV39Dg+Lr7GzhknjPnmZfcHuduxm348=";
        platform = "darwin-arm64";
      };
      aarch64-linux = {
        hash = "sha256-TK6U06vRVpnWpHkQOpo5+zwdzYWmzhkYgvGQI0DxD0Q=";
        platform = "linux-arm64";
      };
      x86_64-linux = {
        hash = "sha256-yRqIdPOyvckFwkUvnZ/JIwE5JP60MeJW63af95JxnX8=";
        platform = "linux-x64";
      };
    };
  };

  grok = {
    version = "1.0.50";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-r0Gx1l1BFv9kmmia2dBw1MKr4lVzfUa6Cz6BYTRWluY=";
        platform = "macos-aarch64";
      };
      aarch64-linux = {
        hash = "sha256-lH7qY+Ujk+AHeNZR0i4NrSLTDp7lsq95RO/D/UQ47MA=";
        platform = "linux-aarch64";
      };
      x86_64-linux = {
        hash = "sha256-yA3gFVcG/y2ZViOIexAvLQq9LGKyZD3qOgzrr33XJNU=";
        platform = "linux-x86_64";
      };
    };
  };

  kimi = {
    version = "1.52.0";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-Q/4JH3C7+IYJdCAPkCGgVomgIIV8yZJtVvFQXw0NXLg=";
        platform = "aarch64-apple-darwin";
      };
      aarch64-linux = {
        hash = "sha256-ngbuqWJzYArtSFsfC+3albcITbTyLPKGFP4gE4kzUHo=";
        platform = "aarch64-unknown-linux-gnu";
      };
      x86_64-linux = {
        hash = "sha256-pnYgT3gE7V2uh2UqnWb1eOBxjVAmycsb+jK5perOQgg=";
        platform = "x86_64-unknown-linux-gnu";
      };
    };
  };

  opencode = {
    version = "1.18.35";
    artifacts = {
      aarch64-darwin = {
        hash = "sha256-eD4NhJqeN0QKnla0ozkUL/0EQQLVnqQ4ZMp+PLvSQVY=";
        platform = "darwin-arm64";
      };
      aarch64-linux = {
        hash = "sha256-9/K6We6KqU04j5aWV1oy0g5xwu5I3vn4D8aTpg/sbHI=";
        platform = "linux-arm64";
      };
      x86_64-linux = {
        hash = "sha256-yPiItFH1SUoY+Fj/+w4LaPTkuqnCQXYcXyBohPD6ZA0=";
        platform = "linux-x64";
      };
    };
  };

  proton-pass = {
    version = "1.42.0";
    artifacts = {
      aarch64-darwin = {
        hash = "sha512-sXWztTKJLgUIYtZg9p6Bvmk7skIDdxBsaaV8kDgCQ3k3Rh3FHsxY47J+iVglKXp2uymUNvcFginYk47BnKwYCw==";
        url = "https://proton.me/download/pass/macos/ProtonPass_1.38.1.dmg";
      };
      x86_64-linux = {
        hash = "sha512-hgVQyHQdoVNJTTgXQyJsnUTPukKzgSOfDwgzNhAdYOJzQMELAMK80qDsXNjCJqToy2BQiUC5z9zAeVhK8DXuyA==";
        url = "https://proton.me/download/pass/linux/proton-pass_1.38.1_amd64.deb";
      };
    };
  };

  vibe = {
    version = "2.26.1";
    artifacts = {
      aarch64-darwin = {
        arch = "darwin-aarch64";
        hash = "sha256-8dOPsNk2x/vJT3HH/hMQrp5PUiJMQ4qUyCZHduVz108=";
      };
      aarch64-linux = {
        arch = "linux-aarch64";
        hash = "sha256-yH++1po4gx4xOzfVS+DM1pP5NFVZvxFTlqlpRCrDTn4=";
      };
      x86_64-linux = {
        arch = "linux-x86_64";
        hash = "sha256-fHRAs5mKOeGDvQrPW2iZ+2HZ1h4/9URH/FcoEL4x1vM=";
      };
    };
  };

  vibe-acp = {
    version = "2.26.1";
    artifacts = {
      aarch64-darwin = {
        arch = "darwin-aarch64";
        hash = "sha256-l6moBuApLRc0gwzUZtFOPj1Q4vJP02bg11l8yHoH1jI=";
      };
      aarch64-linux = {
        arch = "linux-aarch64";
        hash = "sha256-bP51KcZLA9FySmEXJWqnzwCw9YbLyGTmXOpK/5nV114=";
      };
      x86_64-linux = {
        arch = "linux-x86_64";
        hash = "sha256-FdnuPe1IdXlSNXHqXKfx9tt8nwfBq8UZr4EYc+q+1fA=";
      };
    };
  };
}
